name: twochealthcare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^0.14.0+5
  flutter_hooks: ^0.18.0
  flutter_staggered_grid_view: ^0.4.1
  sentry_flutter: ^6.0.1
  syncfusion_flutter_charts: ^19.3.45+1
  flutter_svg: ^0.23.0+1
  page_transition: ^2.0.4
  fluentui_icons: ^1.0.0
  table_calendar: ^3.0.2
  dio: ^4.0.0
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  new_version: ^0.2.3
  firebase_messaging: ^10.0.9
  firebase_core: ^1.8.0
  flutter_local_notifications: ^9.0.1
  shared_preferences: ^2.0.8
  jiffy: ^4.1.0
  package_info: ^2.0.2
  icofont_flutter: ^1.4.0
  signalr_core: ^1.1.1
  rxdart: ^0.27.3
  bot_toast: ^4.0.1
  connectivity_plus: ^2.0.3
  easy_mask: ^2.0.1
  marquee: ^2.2.0
  webview_flutter: ^3.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/loginBg.png
    - assets/icons/logo.svg
    - assets/icons/home/health-guide-icon.svg
    - assets/icons/home/reading-icon.svg
    - assets/icons/home/trophy-icon.svg
    - assets/icons/home/user-icon.svg
    - assets/icons/home/side-menu-icon.svg
    - assets/icons/home/right-arrow-icon.svg
    - assets/icons/side_menu/cross-icon.svg
    - assets/icons/side_menu/home-icon.svg
    - assets/icons/side_menu/logout-icon.svg
    - assets/icons/side_menu/setting-icon.svg
    - assets/icons/readings/blood-glucose-icon.svg
    - assets/icons/readings/heart-icon.svg
    - assets/icons/readings/weight-icon.svg
    - assets/icons/bottom_navbar/user-icon.svg
    - assets/icons/bottom_navbar/message-icon.svg
    - assets/icons/i.svg
    - assets/loader.gif
    - assets/icons/splash_logo.png
    - assets/icons/personIcon.png
    - assets/icons/Icon_Video.svg

  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts_family/poppins/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts_family/poppins/Poppins-Bold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts_family/poppins/Poppins-Medium.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts_family/poppins/Poppins-Thin.ttf





#  With a Dart package, run dart run build_runner build in the package directory.
#
#  With a Flutter package, run flutter pub run build_runner build in your package directory.